services:
  app:
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo
    container_name: mongo_trademap
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
